config-version: 2

name: "jaffle_shop_seed"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 70471823404569 # Put your project id here

profile: default # Put your profile here

seed-paths: ["seeds", "csv"]

seeds:
  jaffle_shop_seed: